### ISSUE TITLE
Work with ws 4.9.1 and 5.x simultaneusly

### ISSUE THREAD

**Issue by willyk0** [lebaston100/node-red-contrib-obs-ws#6]
Hi! I'm finding a bit difficult migrating from WS 4.9.1 to 5.x (I have hundreds of calls to migrate). I have an old version of this node installed, that work with 4.9.1 flawlessly. If I update it to a new version, then my previous code stop working because the node now expects 5.x syntax so I would need to migrate everything in one single step.

It would be great if a fork of the old version could be done and uploaded as a brand new node (node-red-contrib-obs-ws4-compat?) to help doing the migration step by step with proper testing of every call. I would do myself if I knew how to do it, but it's far far far beyond my knowledge about github, npm and node-red package system.

Thank you in advance :)

**Comment by lebaston100** [comment]
Hi. This is unfortunately not possible since some of the internal node names would collide which is unfortunately a global instance-wide scope. That would lead to broken/unusable nodes of one of the versions.
I'd suggest running a 2nd instance of node-red with the new version and migrating that way. Once done you can upgrade the main instance and move the flow file over.
