### ISSUE TITLE
Does not reconnect reliably

### ISSUE THREAD

**Issue by bogorad** [lebaston100/node-red-contrib-obs-ws#7]
Node-red is running on a R-pi4. OBS is on a win10 machine. When win10 machine goes to sleep and later wakes up, reconnecting can take between minutes and hours. Can this be fixed, or at least forced via a command?

**Comment by lebaston100** [comment]
Hi, i was able to replicate this and do a bit of research on this. It happens when the tcp connection is closed by one side without the proper tcp connection is closing data exchange (like disconnecting the ethernet cable or in your case putting the pc to sleep).
You can simply force the disconnect event by ocasionally (on some interval that makes sense for you) sending a simple request like GetRecordStatus. This will then error out trying to make the request and then start a reconnection attempt.
For the future i've added a native ping integration (basically doing the same thing as descibed above) to the todo list.

**Comment by bogorad** [comment]
Thank you! I don't know if this is related, but after the last update, it keeps disconnecting and re-connecting constantly, although the PC is on. Here's a video, it happens every ~30 seconds.

https://capture.dropbox.com/SnrAVp7TbRRKWhrI

UPD: `ws ping` works reliably from my rpi4:

```
ubuntu@living-bruc-controller:~/bin$ ws ping -n 30  ws://192.168.11.30:4455
PING ws://192.168.11.30:4455 with 32 bytes of data
sequence=1, time=0.00s
sequence=2, time=0.00s
sequence=3, time=0.00s
sequence=4, time=0.00s
sequence=5, time=0.00s
sequence=6, time=0.00s
sequence=7, time=0.00s
sequence=8, time=0.00s
sequence=9, time=0.00s
sequence=10, time=0.00s
sequence=11, time=0.00s
sequence=12, time=0.00s
sequence=13, time=0.00s
sequence=14, time=0.00s
sequence=15, time=0.00s
sequence=16, time=0.00s
sequence=17, time=0.00s
sequence=18, time=0.00s
sequence=19, time=0.00s
sequence=20, time=0.00s
sequence=21, time=0.00s
sequence=22, time=0.00s
sequence=23, time=0.00s
sequence=24, time=0.00s
sequence=25, time=0.00s
sequence=26, time=0.00s
sequence=27, time=0.00s
sequence=28, time=0.00s
sequence=29, time=0.00s
sequence=30, time=0.00s
```

**Comment by lebaston100** [comment]
Could you run your node-red in log level "trace" mode and post the output?

**Comment by lebaston100** [comment]
Nevermind, i managed to replicate it and will push a fix shortly.

**Comment by lebaston100** [comment]
Please test again with the latest version

**Comment by bogorad** [comment]
It's fixed now! Thank you very much!
